### ISSUE TITLE
infer.py脚本如何生成不同的数据？

### ISSUE THREAD

**Issue by taofuyu** [Len-Li/Lift3D#5]
请问infer.py脚本在使用时，应该如何调整以生成不同视角、不同车型的车辆数据？以及获取车辆对应的3D信息？谢谢！

**Comment by Len-Li** [comment]
Hi, 

I am sorry for the late reply. You can find the pose information in `curr_pose_azim` and `curr_pose_elev `, which define the azimuth and elevation angle in a sphere. The size of the vehicle is defined using `rays_full_dict["car_size"]`, noted by width, height, and length.

I hope this will help. Feel free to reopen it if you want to have further discussion.
