### ISSUE TITLE
stylegan网络训练

### ISSUE THREAD

**Issue by xuao812500279** [Len-Li/Lift3D#6]
您好，请问你的stylegan网络是如何训练的，它可以生成车的多视角图吗？

**Comment by Len-Li** [comment]
Hi, 

We obtain stylegan weights from [this repo](https://github.com/rosinality/stylegan2-pytorch). It is trained on LSUN car dataset.

After latent optimization, stylegan can generate pseudo-multi-view images. The generated contents are largely multi-view consistent, but minor details may not. Recently, I found that recent work on diffusion model can greatly surpass stylegan, check out [zero123plus](https://github.com/SUDO-AI-3D/zero123plus).

Best,
Leheng Li

**Comment by xuao812500279** [comment]
ok， Thank you for your answer.
